# GitGuardian Configuration
# This file configures secret detection for this repository

version: 2

# Paths to exclude from secret scanning
paths-ignore:
  - "**/*.md"  # Documentation files
  - "**/sql/**"  # SQL files contain example/demo data
  - "**/*_DEMO_*"  # Demo-related files
  - "**/*_EXAMPLE_*"  # Example files
  - "**/docs/**"  # Documentation directory

# Specific patterns to ignore (demo/example hashes only)
matches-ignore:
  - name: Demo bcrypt hashes in documentation
    match: '\$2b\$10\$.*'  # Bcrypt hashes in docs are for examples only

  - name: Example passwords in setup guides
    match: 'Test1234|demo123'  # Common demo passwords
